// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:exam/features/exam/data/models/answer_model.dart';
import 'package:exam/features/exam/data/models/exam_model.dart';
import 'package:exam/features/exam/data/models/question_model.dart';
import 'package:exam/features/exam/data/models/questions_exam_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnswerModelAdapter());
    registerAdapter(ExamModelAdapter());
    registerAdapter(QuestionModelAdapter());
    registerAdapter(QuestionsExamModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnswerModelAdapter());
    registerAdapter(ExamModelAdapter());
    registerAdapter(QuestionModelAdapter());
    registerAdapter(QuestionsExamModelAdapter());
  }
}
